<?php

final class AController extends Symfony\Bundle\FrameworkBundle\Controller\AbstractController
{
    public function method()
    {
        return $this->something();
    }

    private function something()
    {

    }
}
?>
-----
<?php

final class AController extends Symfony\Bundle\FrameworkBundle\Controller\AbstractController
{
    public function method()
    {
        return $this->something();
    }

    private function something()
    {

    }
}
?>